let state=Store.load();ensureItems();
const $=s=>document.querySelector(s), $$=s=>Array.from(document.querySelectorAll(s));
function quoteSubtotal(){return (state.quote||[]).reduce((a,q)=>a+(Number(q.price)||0)*(Number(q.qty)||1),0)}
function persist(){Store.save(state)}
function applyI18n(){document.documentElement.lang=state.settings.lang;$$('[data-i18n]').forEach(el=>el.textContent=t(el.dataset.i18n));$('#pageTitle').textContent=t($('.page.active')?.id==='database'?'database':$('.page.active')?.id==='settings'?'settings':'quote');$('#language').value=state.settings.lang}
function renderQuote(){const box=$('#quoteLines');box.innerHTML='';(state.quote||[]).forEach((q,i)=>{const el=document.createElement('div');el.className='line';el.innerHTML=`<div><b>${escapeHtml(itemName(q))}</b><small>${escapeHtml(q.type||'')}</small></div><div><b>${fmtMoney((q.qty||1)*q.price)}</b><button data-del="${i}">×</button></div>`;box.appendChild(el)});const sub=quoteSubtotal(),vat=sub*(Number(state.settings.vatRate||21)/100),grand=sub+vat;$('#subtotal').textContent=fmtMoney(sub);$('#vat').textContent=fmtMoney(vat);$('#grandTotal').textContent=fmtMoney(grand);$('#sideTotal').textContent=fmtMoney(grand);$('#lineCount').textContent=(state.quote||[]).length+' regels';box.querySelectorAll('[data-del]').forEach(b=>b.onclick=()=>{state.quote.splice(+b.dataset.del,1);persist();renderQuote()})}
function renderDb(){const box=$('#dbList');box.innerHTML='';state.items.forEach((it,i)=>{const el=document.createElement('div');el.className='dbItem';el.innerHTML=`<div><b>${escapeHtml(itemName(it))}</b><small class="tag">${escapeHtml(it.type)}</small><small>${(it.keywords||[]).join(', ')}</small></div><b>${fmtMoney(it.price)}</b><button data-remove="${i}">×</button>`;box.appendChild(el)});box.querySelectorAll('[data-remove]').forEach(b=>b.onclick=()=>{state.items.splice(+b.dataset.remove,1);persist();renderDb()})}
function fillSettings(){const s=state.settings;['companyName','companyEmail','companyPhone','companyWeb','companyAddress','vatRate','validDays'].forEach(id=>{$('#'+id).value=s[id]??''})}
function bind(){setTimeout(()=>$('#splash').classList.add('hide'),2000);if('serviceWorker'in navigator)navigator.serviceWorker.register('./service-worker.js').catch(()=>{});$$('nav button').forEach(btn=>btn.onclick=()=>{$$('nav button').forEach(b=>b.classList.remove('active'));btn.classList.add('active');$$('.page').forEach(p=>p.classList.remove('active'));$('#'+btn.dataset.page).classList.add('active');applyI18n()});$('#language').onchange=e=>{state.settings.lang=e.target.value;persist();applyI18n();renderQuote();renderDb();fillSettings()};$('#themeBtn').onclick=()=>{state.settings.theme=state.settings.theme==='dark'?'light':'dark';document.body.classList.toggle('light',state.settings.theme==='light');persist()};$('#analyze').onclick=()=>{state.quote=analyzeText($('#jobText').value);persist();renderQuote()};$('#clearQuote').onclick=()=>{state.quote=[];$('#jobText').value='';persist();renderQuote()};$('#exportPdf').onclick=exportPdf;$('#addItem').onclick=()=>$('#itemForm').classList.toggle('hidden');$('#saveItem').onclick=()=>{const id=$('#itemKey').value.trim()||('item_'+Date.now());state.items.push({id,type:$('#itemType').value,name:{nl:$('#itemNl').value||id,de:$('#itemDe').value||$('#itemNl').value||id,pl:$('#itemPl').value||$('#itemNl').value||id},keywords:$('#itemKeywords').value.split(',').map(x=>x.trim()).filter(Boolean),price:Number($('#itemPrice').value)||0});['itemKey','itemNl','itemDe','itemPl','itemKeywords','itemPrice'].forEach(id=>$('#'+id).value='');persist();renderDb()};['companyName','companyEmail','companyPhone','companyWeb','companyAddress','vatRate','validDays'].forEach(id=>{$('#'+id).oninput=e=>{state.settings[id]=e.target.value;persist()}})}
function init(){document.body.classList.toggle('light',state.settings.theme==='light');bind();applyI18n();renderQuote();renderDb();fillSettings();persist()}init();
