let state=Store.load();ensureItems();
const $=s=>document.querySelector(s), $$=s=>Array.from(document.querySelectorAll(s));
function escapeHtml(s){return String(s??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
function quoteSubtotal(){return (state.quote||[]).reduce((a,q)=>a+(Number(q.price)||0)*(Number(q.qty)||1),0)}
function persist(){Store.save(state)}
function renderTypeOptions(){const sel=$('#itemType'); if(!sel)return; const val=sel.value||'base'; sel.innerHTML=Object.keys(TYPE_LABELS.nl).map(k=>`<option value="${k}">${typeLabel(k)}</option>`).join(''); sel.value=val in TYPE_LABELS.nl?val:'base'}
function setPlaceholders(){const ph={nl:{job:'Huis van 63 m² met losse garage, parkeren voor de deur, 2 werkdagen',key:'house_50_80',name:'50-80',kw:'huis, woning, appartement'},de:{job:'Haus mit 63 m², freistehende Garage, Parken direkt vor der Tür, 2 Arbeitstage',key:'haus_50_80',name:'50-80',kw:'Haus, Wohnung, Appartement'},pl:{job:'Dom 63 m², wolnostojący garaż, parking przed drzwiami, 2 dni robocze',key:'dom_50_80',name:'50-80',kw:'dom, mieszkanie, apartament'}}[state.settings.lang]; $('#jobText').placeholder=ph.job; $('#itemKey').placeholder=ph.key; $('#itemName').placeholder=ph.name; $('#itemKeywords').placeholder=ph.kw;}
function activePageKey(){return $('.page.active')?.id==='database'?'database':$('.page.active')?.id==='settings'?'settings':'quote'}
function applyI18n(){document.documentElement.lang=state.settings.lang;$$('[data-i18n]').forEach(el=>el.textContent=t(el.dataset.i18n));$('#pageTitle').textContent=t(activePageKey());$('#language').value=state.settings.lang;$('#themeSelect').value=state.settings.theme||'dark';renderTypeOptions();setPlaceholders();renderQuote();renderDb();updateVatLabel()}
function updateVatLabel(){const l=state.settings.lang; const vatWord=l==='de'?'MwSt.':l==='pl'?'VAT':'BTW'; const el=$('#vatLabel'); if(el)el.textContent=`${vatWord} ${state.settings.vatRate||21}%`}
function renderQuote(){const box=$('#quoteLines');box.innerHTML='';(state.quote||[]).forEach((q,i)=>{const label=q.displayName||itemName(q);const meta=[typeLabel(q.type),q.matchedValue?`${t('ranges')}: ${q.matchedValue}`:''].filter(Boolean).join(' · ');const el=document.createElement('div');el.className='line';el.innerHTML=`<div><b>${escapeHtml(label)}</b><small>${escapeHtml(meta)}</small></div><div><b>${fmtMoney((q.qty||1)*q.price)}</b><button data-del="${i}" aria-label="Delete">×</button></div>`;box.appendChild(el)});const sub=quoteSubtotal(),vat=sub*(Number(state.settings.vatRate||21)/100),grand=sub+vat;$('#subtotal').textContent=fmtMoney(sub);$('#vat').textContent=fmtMoney(vat);$('#grandTotal').textContent=fmtMoney(grand);$('#sideTotal').textContent=fmtMoney(grand);$('#lineCount').textContent=(state.quote||[]).length+' '+(state.settings.lang==='de'?'Zeilen':state.settings.lang==='pl'?'pozycji':'regels');updateVatLabel();box.querySelectorAll('[data-del]').forEach(b=>b.onclick=()=>{state.quote.splice(+b.dataset.del,1);persist();renderQuote()})}
function sortedItems(){const order={base:1,area:2,parking:3,floor:4,day:5,extra:6};return state.items.map((it,i)=>({it,i})).sort((a,b)=>(order[a.it.type]||99)-(order[b.it.type]||99)||itemName(a.it).localeCompare(itemName(b.it),state.settings.lang))}
function renderDb(){const box=$('#dbList');box.innerHTML='';sortedItems().forEach(({it,i})=>{const range=(it.min!=null&&it.max!=null)?`${it.min}–${it.max} · ${fmtMoney(it.minPrice)} → ${fmtMoney(it.maxPrice)}`:t('noRange');const kws=kwList(it).join(', ');const el=document.createElement('div');el.className='dbItem';el.innerHTML=`<div class="dbItemMain"><div class="dbItemTitle"><b>${escapeHtml(itemName(it))}</b><small class="tag">${escapeHtml(typeLabel(it.type))}</small></div><div class="dbMeta"><span>${escapeHtml(range)}</span><span>${escapeHtml(t('keywords'))}: ${escapeHtml(kws||'-')}</span></div></div><div class="dbActions"><b>${fmtMoney(itemPriceFor(it,it.min||1))}</b><button data-edit="${i}" title="${t('edit')}">✎</button><button data-remove="${i}">×</button></div>`;box.appendChild(el)});box.querySelectorAll('[data-remove]').forEach(b=>b.onclick=()=>{state.items.splice(+b.dataset.remove,1);persist();renderDb()});box.querySelectorAll('[data-edit]').forEach(b=>b.onclick=()=>openEditItem(+b.dataset.edit))}
function fillSettings(){const s=state.settings;['companyName','companyEmail','companyPhone','companyWeb','companyAddress','vatRate','validDays','customerName','customerStreet','customerPostcodeCity','customerCountry'].forEach(id=>{const el=$('#'+id); if(el)el.value=s[id]??''});$('#language').value=s.lang||'nl';$('#themeSelect').value=s.theme||'dark'}
function clearItemForm(){['editIndex','itemKey','itemName','itemKeywords','itemMin','itemMax','itemMinPrice','itemMaxPrice'].forEach(id=>{$('#'+id).value=''})}
function showItemForm(){ $('#itemForm').classList.remove('hidden'); renderTypeOptions(); setPlaceholders(); setTimeout(()=>$('#itemName').focus(),50); }
function openEditItem(i){const it=state.items[i]; if(!it)return; showItemForm(); $('#editIndex').value=i; $('#itemKey').value=it.id||''; $('#itemType').value=it.type||'base'; $('#itemName').value=it.nameRaw||itemName(it)||''; $('#itemKeywords').value=kwList(it).join(', '); $('#itemMin').value=it.min??''; $('#itemMax').value=it.max??''; $('#itemMinPrice').value=it.minPrice??it.price??''; $('#itemMaxPrice').value=it.maxPrice??it.price??'';}
function saveItem(){const editIndex=$('#editIndex').value; const id=$('#itemKey').value.trim()||('item_'+Date.now()); const min=$('#itemMin').value===''?null:Number($('#itemMin').value), max=$('#itemMax').value===''?null:Number($('#itemMax').value); const minPrice=Number($('#itemMinPrice').value)||0, maxPrice=$('#itemMaxPrice').value===''?minPrice:Number($('#itemMaxPrice').value); const nameText=$('#itemName').value.trim()||id; const keys=tokenKeysFromText(nameText).filter(k=>LEXICON[k]); const keywordKeys=Array.from(new Set([...keys,...tokenKeysFromText($('#itemKeywords').value).filter(k=>LEXICON[k])])); const fallback=$('#itemType').value==='area'?'house':$('#itemType').value==='day'?'workday':$('#itemType').value==='floor'?'floor':$('#itemType').value==='parking'?'parking_front':'base'; const item={id,type:$('#itemType').value,nameKey:keys.join(' ')||fallback,nameRaw:nameText.replace(/^(huis|woning|haus|wohnung|dom|mieszkanie|garage|werkdag|arbeitstag|dzień roboczy)\s*/i,'').trim(),keywordKeys:keywordKeys.length?keywordKeys:keys,min,max,minPrice,maxPrice,price:minPrice}; const normalized=normalizeItem(item); if(editIndex!=='')state.items[Number(editIndex)]=normalized; else state.items.push(normalized); clearItemForm();$('#itemForm').classList.add('hidden');persist();renderDb();}
function bind(){setTimeout(()=>$('#splash').classList.add('hide'),2000);if('serviceWorker'in navigator)navigator.serviceWorker.register('./service-worker.js').catch(()=>{});$$('nav button').forEach(btn=>btn.onclick=()=>{$$('nav button').forEach(b=>b.classList.remove('active'));btn.classList.add('active');$$('.page').forEach(p=>p.classList.remove('active'));$('#'+btn.dataset.page).classList.add('active');applyI18n()});$('#language').onchange=e=>{state.settings.lang=e.target.value;persist();applyI18n();fillSettings()};$('#themeSelect').onchange=e=>{state.settings.theme=e.target.value;document.body.classList.toggle('light',state.settings.theme==='light');persist()};$('#analyze').onclick=()=>{state.quote=analyzeText($('#jobText').value);persist();renderQuote()};$('#clearQuote').onclick=()=>{state.quote=[];$('#jobText').value='';persist();renderQuote()};$('#exportPdf').onclick=exportPdf;$('#addItem').onclick=()=>{clearItemForm();showItemForm()};$('#cancelItem').onclick=()=>{clearItemForm();$('#itemForm').classList.add('hidden')};$('#saveItem').onclick=saveItem;['companyName','companyEmail','companyPhone','companyWeb','companyAddress','vatRate','validDays','customerName','customerStreet','customerPostcodeCity','customerCountry'].forEach(id=>{const el=$('#'+id); if(el)el.oninput=e=>{state.settings[id]=e.target.value;persist(); if(id==='vatRate')renderQuote();}})}
function init(){document.body.classList.toggle('light',state.settings.theme==='light');bind();applyI18n();renderQuote();renderDb();fillSettings();persist()}init();
