let state=Store.load();ensureItems();
const $=s=>document.querySelector(s), $$=s=>Array.from(document.querySelectorAll(s));
function escapeHtml(s){return String(s??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
function quoteSubtotal(){return (state.quote||[]).reduce((a,q)=>a+(Number(q.price)||0)*(Number(q.qty)||1),0)}
function persist(){Store.save(state)}
function renderTypeOptions(){const sel=$('#itemType'); if(!sel)return; const val=sel.value||'base'; sel.innerHTML=Object.keys(TYPE_LABELS.nl).map(k=>`<option value="${k}">${typeLabel(k)}</option>`).join(''); sel.value=val in TYPE_LABELS.nl?val:'base'}
function setPlaceholders(){
 const ph={nl:{job:'Huis van 45 m² met losse garage, parkeren voor de deur, 2 werkdagen',key:'house_30_50',kw:'Trefwoorden, komma gescheiden'},de:{job:'Haus mit 45 m², freistehende Garage, Parken direkt vor der Tür, 2 Arbeitstage',key:'haus_30_50',kw:'Schlüsselwörter, durch Komma getrennt'},pl:{job:'Dom 45 m², wolnostojący garaż, parking przed drzwiami, 2 dni robocze',key:'dom_30_50',kw:'Słowa kluczowe, oddzielone przecinkami'}}[state.settings.lang];
 $('#jobText').placeholder=ph.job; $('#itemKey').placeholder=ph.key;
}
function applyI18n(){document.documentElement.lang=state.settings.lang;$$('[data-i18n]').forEach(el=>el.textContent=t(el.dataset.i18n));$('#pageTitle').textContent=t($('.page.active')?.id==='database'?'database':$('.page.active')?.id==='settings'?'settings':'quote');$('#language').value=state.settings.lang;renderTypeOptions();setPlaceholders();renderQuote();renderDb()}
function renderQuote(){const box=$('#quoteLines');box.innerHTML='';(state.quote||[]).forEach((q,i)=>{const label=q.displayName||itemName(q);const meta=[typeLabel(q.type),q.matchedValue?`${t('ranges')}: ${q.matchedValue}`:''].filter(Boolean).join(' · ');const el=document.createElement('div');el.className='line';el.innerHTML=`<div><b>${escapeHtml(label)}</b><small>${escapeHtml(meta)}</small></div><div><b>${fmtMoney((q.qty||1)*q.price)}</b><button data-del="${i}">×</button></div>`;box.appendChild(el)});const sub=quoteSubtotal(),vat=sub*(Number(state.settings.vatRate||21)/100),grand=sub+vat;$('#subtotal').textContent=fmtMoney(sub);$('#vat').textContent=fmtMoney(vat);$('#grandTotal').textContent=fmtMoney(grand);$('#sideTotal').textContent=fmtMoney(grand);$('#lineCount').textContent=(state.quote||[]).length+' '+(state.settings.lang==='de'?'Zeilen':state.settings.lang==='pl'?'pozycji':'regels');box.querySelectorAll('[data-del]').forEach(b=>b.onclick=()=>{state.quote.splice(+b.dataset.del,1);persist();renderQuote()})}
function renderDb(){const box=$('#dbList');box.innerHTML='';state.items.forEach((it,i)=>{const range=(it.min!=null&&it.max!=null)?`${it.min}–${it.max} → ${fmtMoney(it.minPrice)} / ${fmtMoney(it.maxPrice)}`:t('noRange');const kws=kwList(it).join(', ');const el=document.createElement('div');el.className='dbItem';el.innerHTML=`<div><b>${escapeHtml(itemName(it))}</b><small class="tag">${escapeHtml(typeLabel(it.type))}</small><small>${escapeHtml(range)}</small><small>${escapeHtml(t('keywords'))}: ${escapeHtml(kws)}</small></div><b>${fmtMoney(itemPriceFor(it,it.min||1))}</b><button data-remove="${i}">×</button>`;box.appendChild(el)});box.querySelectorAll('[data-remove]').forEach(b=>b.onclick=()=>{state.items.splice(+b.dataset.remove,1);persist();renderDb()})}
function fillSettings(){const s=state.settings;['companyName','companyEmail','companyPhone','companyWeb','companyAddress','vatRate','validDays'].forEach(id=>{$('#'+id).value=s[id]??''})}
function clearItemForm(){['itemKey','itemNl','itemDe','itemPl','itemKeywordsNl','itemKeywordsDe','itemKeywordsPl','itemMin','itemMax','itemMinPrice','itemMaxPrice'].forEach(id=>{$('#'+id).value=''})}
function saveItem(){
 const id=$('#itemKey').value.trim()||('item_'+Date.now());
 const min=$('#itemMin').value===''?null:Number($('#itemMin').value), max=$('#itemMax').value===''?null:Number($('#itemMax').value);
 const minPrice=Number($('#itemMinPrice').value)||0, maxPrice=$('#itemMaxPrice').value===''?minPrice:Number($('#itemMaxPrice').value);
 const item={id,type:$('#itemType').value,name:{nl:$('#itemNl').value||id,de:$('#itemDe').value||$('#itemNl').value||id,pl:$('#itemPl').value||$('#itemNl').value||id},keywords:{nl:$('#itemKeywordsNl').value.split(',').map(x=>x.trim()).filter(Boolean),de:$('#itemKeywordsDe').value.split(',').map(x=>x.trim()).filter(Boolean),pl:$('#itemKeywordsPl').value.split(',').map(x=>x.trim()).filter(Boolean)},min,max,minPrice,maxPrice,price:minPrice};
 state.items.push(item);clearItemForm();$('#itemForm').classList.add('hidden');persist();renderDb();
}
function bind(){setTimeout(()=>$('#splash').classList.add('hide'),2000);if('serviceWorker'in navigator)navigator.serviceWorker.register('./service-worker.js').catch(()=>{});$$('nav button').forEach(btn=>btn.onclick=()=>{$$('nav button').forEach(b=>b.classList.remove('active'));btn.classList.add('active');$$('.page').forEach(p=>p.classList.remove('active'));$('#'+btn.dataset.page).classList.add('active');applyI18n()});$('#language').onchange=e=>{state.settings.lang=e.target.value;persist();applyI18n();fillSettings()};$('#themeBtn').onclick=()=>{state.settings.theme=state.settings.theme==='dark'?'light':'dark';document.body.classList.toggle('light',state.settings.theme==='light');persist()};$('#analyze').onclick=()=>{state.quote=analyzeText($('#jobText').value);persist();renderQuote()};$('#clearQuote').onclick=()=>{state.quote=[];$('#jobText').value='';persist();renderQuote()};$('#exportPdf').onclick=exportPdf;$('#addItem').onclick=()=>{$('#itemForm').classList.remove('hidden');renderTypeOptions()};$('#cancelItem').onclick=()=>{clearItemForm();$('#itemForm').classList.add('hidden')};$('#saveItem').onclick=saveItem;['companyName','companyEmail','companyPhone','companyWeb','companyAddress','vatRate','validDays'].forEach(id=>{$('#'+id).oninput=e=>{state.settings[id]=e.target.value;persist()}})}
function init(){document.body.classList.toggle('light',state.settings.theme==='light');bind();applyI18n();renderQuote();renderDb();fillSettings();persist()}init();
