const I18N={
 nl:{quote:'Offerte',database:'Database',settings:'Instellingen',describeJob:'Beschrijf opdracht',analyze:'Analyseer offerte',clear:'Leegmaken',subtotal:'Subtotaal excl. BTW',total:'Totaal',totalIncl:'Totaal incl. BTW',offerTo:'Offerte aan',offer:'Offerte',offerNo:'Offertenummer',date:'Datum',qty:'Aantal',desc:'Omschrijving',unit:'Prijs per eenheid',line:'Regeltotaal',valid:'Geldigheid',validText:d=>`Deze offerte is geldig tot ${d}.`,notes:'Opmerkingen',noteText:'Wij danken u voor het vertrouwen en zien uw reactie graag tegemoet.',greeting:'Met vriendelijke groet,',professional:'Professioneel',reliable:'Betrouwbaar',fast:'Snel & Efficiënt',addItem:'+ item',save:'Opslaan',cancel:'Annuleren',key:'Sleutel',type:'Type veld',minAmount:'Minimaal m²/aantal',maxAmount:'Maximaal m²/aantal',minPrice:'Prijs bij minimum',maxPrice:'Prijs bij maximum',ranges:'Bereik',keywords:'Trefwoorden',noRange:'Vaste prijs'},
 de:{quote:'Angebot',database:'Datenbank',settings:'Einstellungen',describeJob:'Auftrag beschreiben',analyze:'Angebot analysieren',clear:'Leeren',subtotal:'Gesamt exkl. MwSt.',total:'Gesamt',totalIncl:'Gesamt inkl. MwSt.',offerTo:'Angebot an',offer:'Angebot',offerNo:'Angebotsnummer',date:'Datum',qty:'Anzahl',desc:'Beschreibung',unit:'Preis pro Einheit',line:'Zeilensumme',valid:'Gültigkeit',validText:d=>`Dieses Angebot ist gültig bis ${d}.`,notes:'Bemerkungen',noteText:'Wir danken Ihnen für Ihr Vertrauen und freuen uns auf Ihre Rückmeldung.',greeting:'Mit freundlichen Grüßen,',professional:'Professionell',reliable:'Zuverlässig',fast:'Schnell & Effizient',addItem:'+ Position',save:'Speichern',cancel:'Abbrechen',key:'Schlüssel',type:'Feldtyp',minAmount:'Minimale m²/Anzahl',maxAmount:'Maximale m²/Anzahl',minPrice:'Preis beim Minimum',maxPrice:'Preis beim Maximum',ranges:'Bereich',keywords:'Schlüsselwörter',noRange:'Festpreis'},
 pl:{quote:'Oferta',database:'Baza danych',settings:'Ustawienia',describeJob:'Opisz zlecenie',analyze:'Analizuj ofertę',clear:'Wyczyść',subtotal:'Razem netto',total:'Razem',totalIncl:'Razem brutto',offerTo:'Oferta dla',offer:'Oferta',offerNo:'Numer oferty',date:'Data',qty:'Ilość',desc:'Opis',unit:'Cena jednostkowa',line:'Suma pozycji',valid:'Ważność',validText:d=>`Oferta jest ważna do ${d}.`,notes:'Uwagi',noteText:'Dziękujemy za zaufanie i czekamy na odpowiedź.',greeting:'Z poważaniem,',professional:'Profesjonalnie',reliable:'Solidnie',fast:'Szybko i sprawnie',addItem:'+ pozycja',save:'Zapisz',cancel:'Anuluj',key:'Klucz',type:'Typ pola',minAmount:'Minimalne m²/liczba',maxAmount:'Maksymalne m²/liczba',minPrice:'Cena przy minimum',maxPrice:'Cena przy maksimum',ranges:'Zakres',keywords:'Słowa kluczowe',noRange:'Cena stała'}
};
const TYPE_LABELS={
 nl:{base:'Basisobject',area:'m² bereik',parking:'Parkeren',floor:'Verdieping',day:'Werkdag',extra:'Extra'},
 de:{base:'Grundobjekt',area:'m²-Bereich',parking:'Parken',floor:'Etage',day:'Arbeitstag',extra:'Extra'},
 pl:{base:'Obiekt bazowy',area:'Zakres m²',parking:'Parking',floor:'Piętro',day:'Dzień roboczy',extra:'Dodatkowe'}
};
function t(k){const l=state.settings.lang;return I18N[l][k]||I18N.nl[k]||k}
function typeLabel(k){const l=state.settings.lang;return (TYPE_LABELS[l]||TYPE_LABELS.nl)[k]||k}
function fmtMoney(v){const l=state.settings.lang;return new Intl.NumberFormat(l==='de'?'de-DE':l==='pl'?'pl-PL':'nl-NL',{style:'currency',currency:'EUR'}).format(v||0)}
function fmtDate(d){const l=state.settings.lang;return new Intl.DateTimeFormat(l==='de'?'de-DE':l==='pl'?'pl-PL':'nl-NL').format(d)}
